### ISSUE TITLE
Third Party Caveat verification id

### ISSUE THREAD

**Issue by cmckni3** [localmed/ruby-macaroons#21]
Macaroons generated with [macaroons.js](https://github.com/nitram509/macaroons.js) fail when decoding with an invalid Base64 error.

**Comment by ecordell** [comment]
Could you provide a failing example (could just be the final, encoded macaroon)?

**Comment by cmckni3** [comment]
Sure. Macaroons.js doesn't base64 the binary ciphertext when generating the verification id. The binary verification id just gets run through the binary serializer.

Below is the binary serialization of the macaroon generated by macaroons.js and the stack trace from ruby-macaroons.

```
MDAyNGxvY2F0aW9uIGNvbS5pc2NncnAuc3NvLnNlc3Npb24KMDAzMGlkZW50aWZpZXIgZTYzZjYwZjZjYTg0MTYxYWRmYmZmMjBkMjU3ODcyYzkKMDAxMGNpZCByb2xlczoxCjAwNTF2aWQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHNljDzNPOnh-OoMWkBPDpNhpZJeAXHGqJalR7YFrbUfSRJ5aj6BFXNW    32x_uKIgPCjAwMWNjbCBjb20uaXNjZ3JwLnNzby5yb2xlcwowMDBmY2lkIGxkYXA6MQowMDUxdmlkIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIggFbrJcvirhlj_YSf9mo9DKIE_Yashpm1W-1nikgI122ZSne3adHPvXdP2FnGf2AowMDFiY2wgY29tLmlzY2dycC5zc28ubGRhcAowMDE0Y2lkIHZpZXdwb2ludDoxCjAwNTF2aWQgAAAAAAAAAAAAAAAAAAA    AAAAAAAAAAAAA4V7xySmYITS82K2sO7GHMpEII6l_ZpbHQkdfbf48zN2BppdB6dDY1GDiRXkP5cibCjAwMjBjbCBjb20uaXNjZ3JwLnNzby52aWV3cG9pbnQKMDAyZnNpZ25hdHVyZSCaO5_5kGkzTPbSnpaTO04vrEPBimIeJ1Mqq5GLZxw3NAo
```

```
/Users/cmcknight/.rbenv/versions/2.1.5/lib/ruby/2.1.0/base64.rb:73:in `unpack': invalid base64 (ArgumentError)
  from /Users/cmcknight/.rbenv/versions/2.1.5/lib/ruby/2.1.0/base64.rb:73:in `strict_decode64'
  from /Users/cmcknight/code/ruby/ruby-macaroons/lib/macaroons/verifier.rb:100:in `extract_caveat_key'
  from /Users/cmcknight/code/ruby/ruby-macaroons/lib/macaroons/verifier.rb:80:in `verify_third_party_caveat'
  from /Users/cmcknight/code/ruby/ruby-macaroons/lib/macaroons/verifier.rb:55:in `block in verify_caveats'
  from /Users/cmcknight/code/ruby/ruby-macaroons/lib/macaroons/verifier.rb:51:in `each'
  from /Users/cmcknight/code/ruby/ruby-macaroons/lib/macaroons/verifier.rb:51:in `verify_caveats'
  from /Users/cmcknight/code/ruby/ruby-macaroons/lib/macaroons/verifier.rb:36:in `verify_discharge'
  from /Users/cmcknight/code/ruby/ruby-macaroons/lib/macaroons/verifier.rb:30:in `verify'
  from macaroon.rb:77:in `<main>'
```

**Comment by ecordell** [comment]
Ah, okay. Without comparing implementations my instinct is that the vid should be base64 encoded first, since the binary serialization format is currently restricted to ascii. 

But I'll look around and see what other macaroon libraries are doing before closing this.

**Comment by cmckni3** [comment]
I don't think the ascii restriction should matter though in the binary serialization because it ends up being converted to base64 at the end of binary serialization.

I think it would be invalid when serialized to JSON and needs to be converted to base64 when serializing to JSON.

**Comment by ecordell** [comment]
I was misremembering the binary format (it's hard to keep straight since there's no formal spec). Went back and reviewed it and the vid isn't encoded in the serialized macaroon (though it is encoded in some cases, such as for display)

**Comment by ecordell** [comment]
Just updated the library to 0.6.0, which should now be compatible with macaroons.js. Reopen/let me know if it doesn't work!

Thanks for the bug hunting!

**Comment by cmckni3** [comment]
Sweet! I saw just your commit and looks good to me.

That's the changes I had to end up making to the PHP implementation.

Sorry for not sending a PR. I wanted to discuss it with you first.
