### ISSUE TITLE
Stricter callbacks?

### ISSUE THREAD

**Issue by nyarly** [localmed/ruby-macaroons#23]
I was checking out how the Verifier works and noticed this line in `verify_first_party_caveat`:

```
caveat_met = true if callback.call(caveat.caveat_id)
```

This is concerning since, because of Ruby's default-return semantics, it becomes very easy to write callbacks that will return a truthy value accidentally. It seems safer to:

```
caveat_met = true if callback.call(caveat.caveat_id) == true
```

**Comment by ecordell** [comment]
This is a good suggestion - always better to make it harder to make mistakes.

I've made this change and update the library.

Thanks!
