### ISSUE TITLE
Consider rbnacl-libsodium

### ISSUE THREAD

**Issue by tarcieri** [localmed/ruby-macaroons#25]
rbnacl-libsodium provides libsodium in a gem form (ala a `-sys` crate in Rust):

https://github.com/cryptosphere/rbnacl-libsodium

It installs on both MRI and JRuby, and I keep it relatively up-to-date (generally updated same day). It removes the need to install libsodium as a separate dependency, and should help people use this gem more easily.

**Comment by ecordell** [comment]
That's a great idea - there's a similar project for python I've been meaning to switch to. I'll plan to switch it sometime in the next few days, or if you get to it before me I'll be happy to merge a PR.

Thanks!

**Comment by tarcieri** [comment]
PR in #26
