### ISSUE TITLE
Dependency/Release Issues, New Rubygems Release Needed

### ISSUE THREAD

**Issue by grempe** [localmed/ruby-macaroons#30]
Version 0.7.0 (12/23/2015)  is the latest release on rubygems.org:

https://rubygems.org/gems/macaroons/versions

This version has a dependency on `multi_json` `~> 1.10.1`

That version of `multi_json` was released on 5/20/2014 and is badly out of date. The current version is `1.12.1`. However, your dependency as stipulated in v0.7.0 will not allow use of anything newer than the last 1.10.x release which was in 2014.

In your master branch, I see you relaxed this dependency which would allow installing `macaroons` alongside other modern gems which depend on `multi_json`. There is no release of this code on Rubygems though.

https://github.com/localmed/ruby-macaroons/blob/master/macaroons.gemspec#L19

Can you please cut a new release from master if it is ready? Without the new release projects have to pull your gem from github master branch.

Also, the github releases page for this project does not have a release or tag for version `0.7.0`. It might be helpful to add that, as well as one for any new release.

https://github.com/localmed/ruby-macaroons/releases

Cheers.

**Comment by petebrowne** [comment]
Thanks - I've tagged 0.7.0, and released a 0.7.1 with the new multi_json dependency

**Comment by grempe** [comment]
Thanks for the quick release Pete! I am able to bundle it in a project now.
