### ISSUE TITLE
Update rbnacl dependency

### ISSUE THREAD

**Issue by Keruspe** [localmed/ruby-macaroons#32]
Currently, the rbnacl dependency is pinned to 3.x, whilst the latest available is 5.0

**Comment by petebrowne** [comment]
Would you be interested in working on a PR? Contributions are welcome

**Comment by thisismeleaving** [comment]
Sure!

**Comment by Keruspe** [comment]
@petebrowne would it be possible to issue some new release on rubygem with this included?

**Comment by petebrowne** [comment]
Yes, sorry it took so long. Release as [1.0.0](https://rubygems.org/gems/macaroons)
